export { api } from '../convex/_generated/api'
export { ConvexBetterAuthProvider } from '@convex-dev/better-auth/react'
export { nextJsHandler } from '@convex-dev/better-auth/nextjs'
export { getToken } from '@convex-dev/better-auth/nextjs'
export { getSessionCookie } from 'better-auth/cookies'
