import type { Metadata } from 'next'
import { Fira_Code, Lora, Space_Grotesk } from 'next/font/google'

import NavBar from '@/components/header'
import { Providers } from '@/components/providers'
import BottomNavigationClient from '@/components/bottom-navigation-client'

import '@cu-forum/ui/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
})

export const firaCodeMono = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
})

export const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Providers>
          <NavBar />
          {children}
          <BottomNavigationClient />
        </Providers>
      </body>
    </html>
  )
}
